Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Prototype.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Net.Http;
using System.Text.Json;
using Prototype.Pages;
using Microsoft.Extensions.Configuration;

namespace Prototype.Pages
{
    public class IndexModel : PageModel
    {
        private readonly NGeniusManager _ngenius;
        private readonly IConfiguration _config;
        public IndexModel(IConfiguration config)
        {
            _config = config;
            _ngenius = new NGeniusManager(_config);
        }

        public void OnGet()
        {
            var token = new NGeniusTokenResponse();
            var error = new NGeniusErrorResponse();
            ViewData["Message"] =NGeniusToken.Value.access_token;
        }
    }
}

Pages/Order.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;

namespace Prototype.Pages
{
    public class OrderModel : PageModel
    {
        private readonly IConfiguration _config;
        private readonly NGeniusManager _ngenius;
        public OrderModel(IConfiguration config)
        {
            _config = config;
            _ngenius = new NGeniusManager(_config);
        }
        public class OrderQuery
        {
            [BindProperty]
            public string OrderID { get; set; }
        }
        public void OnPostSubmit(OrderQuery order)
        {
            NGeniusErrorResponse err = new NGeniusErrorResponse();
            _ngenius.UpdateOrder(_ngenius.Config.OutletID,order.OrderID ,ref err);
            ViewData["DataSource"] = _ngenius.GetOrder(_ngenius.Config.OutletID, ref err);
            ViewData["Message"] = err.message;
        }
        public void OnGet()
        {
            NGeniusErrorResponse err = new NGeniusErrorResponse();
            ViewData["DataSource"] = _ngenius.GetOrder(_ngenius.Config.OutletID,ref err);
            ViewData["Message"] = err.message;
        }
    }
}

Pages/Payment.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;

namespace Prototype.Pages
{
    public class PaymentModel : PageModel
    {
        private readonly IConfiguration _config;
        private readonly NGeniusManager _ngenius;
        public PaymentModel(IConfiguration config)
        {
            _config = config;
            _ngenius = new NGeniusManager(_config);
        }
        public void OnGet()
        {
            ViewData["Message"] = NGeniusToken.Error.message;
        }
        public void OnPostSubmit(CardPaymentParams payment)
        {
            NGeniusErrorResponse err = new NGeniusErrorResponse();
            NGeniusPayment res = new NGeniusPayment();
            _ngenius.CreateCardPayment(payment, ref err, ref res);
            if (err.code == 100)
            {
                _ngenius.SaveOrder(res, ref err);
                ViewData["Message"] = "Order ID:" + res.orderReference + "<br>Payment ID:" + res.reference +"<br>" + err.message;
            } else
            {
                ViewData["Message"] = err.message;
            }
        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Prototype.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly IConfiguration _config;
        private NGeniusManager _ngenius;
        public PrivacyModel(IConfiguration config)
        {
            _config = config;
            _ngenius = new NGeniusManager(_config);
        }

        public void OnGet()
        {
            _ngenius.UpdateToken();
            ViewData["Message"] = NGeniusToken.Error.message;
        }
    }
}

Pages/Project.cshtml.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Net;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Prototype;
namespace Prototype.Pages
{    
    public class ProjectModel : PageModel
    {
        private readonly IConfiguration _config;
        private readonly NGeniusManager _ngenius;
        public ProjectModel(IConfiguration config)
        {
            _config = config;
            _ngenius = new NGeniusManager(_config);
        }
        public string Token { get; set; }
        public string Message { get; set; }
        public OrderParams Order { get; set; }
        public void OnGet()
        {
            var token = new NGeniusTokenResponse();
            var error = new NGeniusErrorResponse();
            Token = NGeniusToken.Value.access_token;
            Message = NGeniusToken.Error.message;
        }
        public void OnPostSubmit(OrderParams order)
        {
            Token = NGeniusToken.Value.access_token;
            NGeniusOrder orderCreate=new NGeniusOrder();
            string msg = "";
            bool chk=_ngenius.CreateOrder(order,ref orderCreate,ref msg);
            var err = new NGeniusErrorResponse();
            if (chk) _ngenius.SaveOrder(orderCreate, ref err);
            Message = (chk? @"OK=<a href=""" + orderCreate._links.payment.href +@""">"+ orderCreate._links.payment.href + "</a>" :"ERROR=" + msg);
        }
    }
}

Pages/TestOrder.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using System.Text.Json;
namespace Prototype.Pages
{
    public class TestOrderModel : PageModel
    {
        public class TestOrder
        {
            [BindProperty]
            public string dataPost { get; set; }
        }
        private readonly IConfiguration _config;
        private readonly NGeniusManager _ngenius;

        public TestOrderModel(IConfiguration config)
        {
            _config = config;
            _ngenius = new NGeniusManager(_config);
        }
        public void OnGet()
        {
            ViewData["Message"] = "Ready";
        }
        public void OnPostSubmit(TestOrder data)
        {
            string Message = "";
            try
            {
                var obj = JsonSerializer.Deserialize<NGeniusOrder>(data.dataPost);
                Message = JsonSerializer.Serialize(obj);
            } catch(Exception e)
            {
                Message = e.Message;
            }
            ViewData["Message"] = Message;
        }
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>

Pages/Order.cshtml
@page
@model Prototype.Pages.OrderModel
<h1>Order List</h1>
<form method="post">
    @{
        <b>@ViewData["Message"]</b>
        <table class="table table-responsive">
            <thead>
                <tr>
                    <th>Type</th>
                    <th>Amount</th>
                    <th>Link Payment</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @{
                    var dt = (System.Data.DataTable)ViewData["DataSource"];
                    foreach (System.Data.DataRow dr in dt.Rows)
                    {
                        <tr>
                            <td>@dr["transType"].ToString()</td>
                            <td>@dr["amountValue"].ToString() @dr["currencyCode"].ToString()</td>
                            <td><a href="@dr["requestURL"].ToString()">@dr["orderRef"].ToString()</a></td>
                            <td>
                                @dr["status"].ToString()
                            </td>
                            <td><input type="submit" class="btn btn-primary" asp-page-handler="Submit" onclick="SetFormValue('@dr["orderRef"].ToString()')" value="Check" /></td>
                        </tr>
                    }
                }
            </tbody>
        </table>
        <input type="hidden" id="txtOrderID" name="OrderID" value="" />
    }
</form>
<script type="text/javascript">
    function SetFormValue(str) {
        document.getElementById("txtOrderID").setAttribute("value", str);
    }
</script>

Pages/Payment.cshtml
@page
@model Prototype.Pages.PaymentModel
<h1>Donation Payment</h1>
<form method="post">
    <input type="hidden" name="action" value="SALE" />
    <table>
        <tr>
            <td>Currency : </td>
            <td><input type="text" id="txtCurrency" name="currencyCode" value="GNF"/></td>
        </tr>
        <tr>
            <td>Amount : </td>
            <td><input type="number" id="txtAmount" name="amount" /></td>
        </tr>
        <tr>
            <td>Card Number :</td>
            <td>
                <input type="text" id="txtCardNumber" name="pan" />
            </td>
        </tr>
        <tr>
            <td>Expiry :</td>
            <td>
                <input type="text" id="txtExpiry" name="expiry" />
            </td>
        </tr>
        <tr>
            <td>CVV :</td>
            <td><input type="password" id="txtCVV" name="cvv" /></td>
        </tr>
        <tr>
            <td>Card Holder Name :</td>
            <td><input type="text" id="txtCardholder" name="cardholderName" /></td>
        </tr>
    </table>
    <input type="submit" asp-page-handler="Submit" value="Submit" />
</form>
<b>@Html.Raw(ViewData["Message"])</b>

Pages/Project.cshtml
@page
@model Prototype.Pages.ProjectModel
@{
    ViewData["Title"] = "Project Donation";
}
<div class="text-left">
    <h1>@ViewData["Title"]</h1>
    <form method="post">
        <table>
            <tr>
                <td>Transaction Type :</td>
                <td>
                    <select name="action" id="cboAction">
                        <option value="SALE">SALES INVOICE</option>
                        <option value="PURCHASE">PURCHASE INVOICE</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    Currency :
                </td>
                <td>
                    <input type="text" id="txtCurrency" name="currencyCode" value="GNF" readonly />
                </td>
            </tr>
            <tr>
                <td>
                    Value :
                </td>
                <td>
                    <input type="number" id="txtAmount" name="amount" />
                </td>
            </tr>
        </table>
        <input type="submit" value="Submit" asp-page-handler="Submit" />
    </form>
    @Html.Raw(Model.Message)
</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Prototype</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Prototype</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Project">Project</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Order">Order</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Payment">Payment</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Prototype - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Pages/TestOrder.cshtml
@page
@model Prototype.Pages.TestOrderModel
@{
}
<form method="post">
    <textarea id="txtValue" name="dataPost"></textarea>
    <input type="submit" asp-page-handler="Submit" value="Submit" />
</form>
@ViewData["Message"]
<script type="text/javascript">
    var obj = {
        "_id": "urn:order:b185dd9d-385a-4681-8a91-fdf6dd21b851",
        "_links": {
            "cancel": {
                "href": "https://api-gateway.sandbox.orabankgn.ngenius-payments.com/transactions/outlets/4150ebb0-7167-4c8f-a104-ab24cb295964/orders/b185dd9d-385a-4681-8a91-fdf6dd21b851/cancel"
            },
            "cnp:payment-link": {
                "href": "https://api-gateway.sandbox.orabankgn.ngenius-payments.com/transactions/outlets/4150ebb0-7167-4c8f-a104-ab24cb295964/orders/b185dd9d-385a-4681-8a91-fdf6dd21b851/payment-link"
            },
            "payment-authorization": {
                "href": "https://api-gateway.sandbox.orabankgn.ngenius-payments.com/transactions/paymentAuthorization"
            },
            "self": {
                "href": "https://api-gateway.sandbox.orabankgn.ngenius-payments.com/transactions/outlets/4150ebb0-7167-4c8f-a104-ab24cb295964/orders/b185dd9d-385a-4681-8a91-fdf6dd21b851"
            },
            "tenant-brand": {
                "href": "http://config-service/config/outlets/4150ebb0-7167-4c8f-a104-ab24cb295964/configs/tenant-brand"
            },
            "payment": {
                "href": "https://paypage.sandbox.orabankgn.ngenius-payments.com/?code=abbb39e0c638b7e3"
            },
            "merchant-brand": {
                "href": "http://config-service/config/outlets/4150ebb0-7167-4c8f-a104-ab24cb295964/configs/merchant-brand"
            }
        },
        "type": "SINGLE",
        "merchantDefinedData": {},
        "action": "SALE",
        "amount": {
            "currencyCode": "GNF",
            "value": 100
        },
        "language": "en",
        "merchantAttributes": {},
        "reference": "b185dd9d-385a-4681-8a91-fdf6dd21b851",
        "outletId": "4150ebb0-7167-4c8f-a104-ab24cb295964",
        "createDateTime": "2024-02-10T07:49:08.904Z",
        "paymentMethods": {
            "card": [
                "MASTERCARD",
                "VISA"
            ]
        },
        "referrer": "urn:Ecom:b185dd9d-385a-4681-8a91-fdf6dd21b851",
        "formattedAmount": "GNF 100",
        "formattedOrderSummary": {},
        "_embedded": {
            "payment": [{
                "_id": "urn:payment:1a1b6c36-41ce-4a90-8e73-94d9ffb7749f",
                "_links": {
                    "self": {
                        "href": "https://api-gateway.sandbox.orabankgn.ngenius-payments.com/transactions/outlets/4150ebb0-7167-4c8f-a104-ab24cb295964/orders/b185dd9d-385a-4681-8a91-fdf6dd21b851/payments/1a1b6c36-41ce-4a90-8e73-94d9ffb7749f"
                    },
                    "payment:card": {
                        "href": "https://api-gateway.sandbox.orabankgn.ngenius-payments.com/transactions/outlets/4150ebb0-7167-4c8f-a104-ab24cb295964/orders/b185dd9d-385a-4681-8a91-fdf6dd21b851/payments/1a1b6c36-41ce-4a90-8e73-94d9ffb7749f/card"
                    },
                    "curies": [{
                        "name": "cnp",
                        "href": "https://api-gateway.sandbox.orabankgn.ngenius-payments.com/docs/rels/{rel}",
                        "templated": true
                    }]
                },
                "reference": "1a1b6c36-41ce-4a90-8e73-94d9ffb7749f",
                "state": "STARTED",
                "amount": {
                    "currencyCode": "GNF",
                    "value": 100
                },
                "updateDateTime": "2023-02-10T07:49:08.904Z",
                "outletId": "4150ebb0-7167-4c8f-a104-ab24cb295964",
                "orderReference": "b185dd9d-385a-4681-8a91-fdf6dd21b851"
            }]
        }
    }

    var json = JSON.stringify(obj);
    document.getElementById("txtValue").value = json;
</script>